### ISSUE TITLE
Module structure

### ISSUE THREAD

**Issue by jbednar** [thomasdeneux/param_qt#2]
Right now, this repo is structured as:

thomasdeneux/param_qt/README.md
thomasdeneux/param_qt/ParamQt.py
thomasdeneux/param_qt/test_ParamQt.py
thomasdeneux/param_qt/test_ParamQt.png

I'd recommend some changes to make it fit in better with the Python ecosystem:

- Packages with "_" or "-" behave strangely between Python and pip; I'd remove those characters from any module or package names, as suggested by https://www.python.org/dev/peps/pep-0008/#package-and-module-names.
- Python code needs to be in a separate subdirectory so that it can be imported easily as a package.
- Typical conventions are to make the github repo name match the Python module name
- There needs to be a LICENSE file before anyone else can use this code
- It's nice if the tests are included in the module so that installed packages can be tested

I.e., I'd recommend reorganizing the files and module name and directory structure to:

thomasdeneux/paramqt/README.md
thomasdeneux/paramqt/LICENSE.txt (feel free to copy https://github.com/holoviz/param/blob/master/LICENSE.txt if you want the same license as Param)
thomasdeneux/paramqt/paramqt/`__init__.py`  (fomerly ParamQt.py)
thomasdeneux/paramqt/paramqt/tests/test_paramqt.py (formerly test_ParamQt.py)
thomasdeneux/paramqt/doc/_static/paramqt_example.png (formerly test_ParamQt.png)

Some people don't like code in `__init__.py`, in which case you could move `ParamQt.py` to `paramqt/paramqt.py` and make a dummy `__init__.py` file containing only:

`
from .paramqt import *
`

**Comment by thomasdeneux** [comment]
Thank you for these comments. Of course the current structure is not correct, i just did it fast to show my code in a better way than a `param` pull request. But i am glad that you give me the best practices and will apply them soon.

**Comment by thomasdeneux** [comment]
done!

**Comment by jbednar** [comment]
Oops; I just noticed that doc/ ended up in thomasdeneux/paramqt/paramqt/ . It should be one level back, i.e. thomasdeneux/paramqt/; it's not part of the Python module.

**Comment by thomasdeneux** [comment]
done; 'tests' also add to be moved one level up, isn't it?
(besides, i don't forget Issue 1 and the promised PR to param, but this might take time as i am quite busy nowasdays)

**Comment by jbednar** [comment]
Thanks!  There are two main views on 'tests', either:

1. They should be at the main level or otherwise outside of the module, because they are not required for normal operation, and therefore waste space in a user install and are distracting for someone wanting to look just at the code or search within it
2. They should be a subdirectory inside the python module, because only the module is included in installable packages (pip, conda, etc.), and otherwise there is no straightforward way to test the packaged module fully to ensure that it has been installed properly.  Moreover, the tests and code should together be thought of a unit, and so if you're searching the module for something to update, you almost certainly need to make the corresponding update to the tests, so it makes sense to manage the combination of code + tests together as a unit.

For my part, I hold opinion 2. But some people very strongly hold opinion 1.
